# Generated by Django 6.0.6 on 2026-07-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'is_active'], name='orders_orde_created_e84566_idx'),
        ),
    ]
