# Generated by Django 6.0.6 on 2026-07-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_product_supplier_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('movement_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış')], db_index=True, max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='stock_stock_product_467980_idx'), models.Index(fields=['movement_type', 'created_at'], name='stock_stock_movemen_9bd0ad_idx'), models.Index(fields=['source_type', 'source_id'], name='stock_stock_source__665c5b_idx')],
            },
        ),
    ]
