# Generated by Django 6.0.6 on 2026-07-09 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('operations', 'İdari İşler'), ('department', 'Birim Kullanıcısı')], db_index=True, default='department', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='accounts_us_role_af860b_idx'), models.Index(fields=['department', 'is_active'], name='accounts_us_departm_0c1ce1_idx')],
            },
        ),
    ]
