# Generated by Django 6.0.6 on 2026-07-09 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='requester_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['requester_user', 'created_at'], name='requisition_request_8447db_idx'),
        ),
    ]
