# Generated by Django 6.0.6 on 2026-07-10 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_supplier_links'),
        ('requisitions', '0002_stockrequest_requester_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequestitem',
            name='requested_product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockrequestitem',
            name='requested_product_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockrequestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_request_items', to='catalog.product'),
        ),
    ]
