# Generated by Django 6.0.6 on 2026-07-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_product_supplier_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('department', models.CharField(db_index=True, max_length=120)),
                ('requester_name', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('purchase_needed', 'Tedarik bekliyor'), ('fulfilled', 'Teslim edildi'), ('cancelled', 'İptal edildi')], db_index=True, default='pending', max_length=30)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='requisition_status_3b24a5_idx'), models.Index(fields=['department', 'created_at'], name='requisition_departm_eb4c9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_request_items', to='catalog.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.stockrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
